name: 部署 CF Workers

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: 部署 ${{matrix.project}}
    strategy:
      fail-fast: false
      matrix:
        project: ${{ vars.PROJECT_NAMES }}

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 初始化环境
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
      
      - name: 配置 ${{matrix.project}}
        run: |
          sed 's/^name = ".*"$/name = "${{matrix.project}}"/g' wrangler.toml

      - name: 部署 ${{matrix.project}}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: 删除旧的 workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 10
