name: 部署到 Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    name: 部署到 Cloudflare Worker
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 初始化环境
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: 部署
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: 删除旧的 workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 10
